Repository codesquad-masters2025-team04/issue-tracker, pull requests merged in 2025-05, with the labels that each got.

#5 [CHORE] erd 이미지 추가
  README.md
  docs/erd.png
Labels: Chore

#7 [CHORE]프로젝트 초기 환경 세팅
  .gitignore
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/codesquad/team4/issuetracker/IssuetrackerApplication.java
  backend/src/main/resources/application.yml
  backend/src/test/java/codesquad/team4/issuetracker/IssuetrackerApplicationTests.java
Labels: Chore

#10 [Feat] 이슈, 레이블, 마일스톤 개수 조회
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueCountService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueCountDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelController.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelService.java
  backend/src/main/java/codesquad/team4/issuetracker/label/dto/LabelCountDto.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneController.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneService.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/dto/MilestoneCountDto.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueCountServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/label/LabelServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/milestone/MilestoneServiceTest.java
Labels: feat

#11 [FEAT] 이슈 목록 구현하기
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/App.module.css
  frontend/src/assets/icons/alertCircle.svg
  frontend/src/assets/icons/archive.svg
  frontend/src/assets/icons/checkBoxInitial.svg
  frontend/src/assets/icons/chevronDown.svg
  frontend/src/assets/icons/milestone.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/images/logoMedium.svg
  frontend/src/assets/images/userImage.png
  frontend/src/components/Dashboard/ClosedIssuePage.jsx
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/IssueList.module.css
  frontend/src/components/Dashboard/IssueTable.jsx
  frontend/src/components/Dashboard/IssueTable.module.css
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Header.module.css
  frontend/src/constants/link.js
  frontend/src/main.css
  frontend/src/main.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/styles/reset.css
  frontend/src/styles/tokens.css
  frontend/vite.config.js
Labels: feat

#18 [Feat] 이슈 생성 API 구현
  backend/build.gradle
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3Config.java
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3FileService.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Comment.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Issue.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueAssignee.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueLabel.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Label.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Milestone.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/User.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/IssueLabelRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/user/IssueAssigneeRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/schema.sql
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
Labels: feat, BE

#22 [Chore] 배포 설정 수정
  backend/src/main/java/codesquad/team4/issuetracker/config/WebConfig.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/resources/application.yml
Labels: Chore, BE

#25 [Refactor] IssueService 리팩토링 및 리뷰 반영
  .gitignore
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3FileService.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueCountService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelDao.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelService.java
  backend/src/main/java/codesquad/team4/issuetracker/label/dto/LabelDto.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneDao.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneService.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/dto/MilestoneDto.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserDao.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserService.java
  backend/src/main/java/codesquad/team4/issuetracker/user/dto/UserDto.java
  backend/src/main/resources/application.yml
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueCountServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/label/LabelServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/milestone/MilestoneServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/user/UserServiceTest.java
Labels: refactor, BE

#26 [FEAT] 완료 버튼 클릭 시 이슈 목록 페이지가 나타나게 구현
  frontend/src/components/ControlHeader/ControlHeader.module.css
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/IssueTable.module.css
  frontend/src/components/Dashboard/WriteIssue.jsx
  frontend/src/components/Dashboard/WriteIssue.module.css
  frontend/src/components/common/PopupList.jsx
Labels: feat, FE

#28 [Feat] 이슈 생성 및 조회 기능 구현, 배포 설정
  .gitignore
  README.md
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/codesquad/team4/issuetracker/IssuetrackerApplication.java
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3Config.java
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3FileService.java
  backend/src/main/java/codesquad/team4/issuetracker/config/WebConfig.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Comment.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Issue.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueAssignee.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueLabel.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Label.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Milestone.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/User.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/ExceptionMessage.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/IssueStatusUpdateException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueCountDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/IssueLabelRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelController.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelDao.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelService.java
  backend/src/main/java/codesquad/team4/issuetracker/label/dto/LabelDto.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneController.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneDao.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneService.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/dto/MilestoneDto.java
  backend/src/main/java/codesquad/team4/issuetracker/user/IssueAssigneeRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserController.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserDao.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserService.java
  backend/src/main/java/codesquad/team4/issuetracker/user/dto/UserDto.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/schema.sql
  backend/src/test/java/codesquad/team4/issuetracker/IssuetrackerApplicationTests.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueCountServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/label/LabelServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/milestone/MilestoneServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/user/UserServiceTest.java
  docs/erd.png
Labels: feat, refactor, Chore, BE

#41 [Feat] 이슈 수정 API 구현
  backend/.gitignore
  backend/src/main/java/codesquad/team4/issuetracker/entity/Comment.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Issue.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueAssignee.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/IssueLabel.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Label.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Milestone.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/User.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/AssigneeNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/ExceptionMessage.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/IssueNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/LabelNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/MilestoneNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/IssueLabelRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelController.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelDao.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneController.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/user/IssueAssigneeRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserController.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserDao.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceUpdateTest.java
  backend/src/test/java/codesquad/team4/issuetracker/util/TestDataHelper.java
  backend/src/test/resources/application-test.yml
Labels: feat, BE

#38 [Chore] name에서 title로 변경
  frontend/src/components/Dashboard/WriteIssue.jsx
Labels: Chore

#46 [chore] 깃헙 액션 워크플로우 작성
  .github/workflows/deploy.yml
Labels: Chore, BE

#47 [chore] ci/cd 워크플로우 작성
  .github/workflows/deploy.yml
Labels: Chore, BE

#48 [FEAT] 이슈 상세 페이지 구현
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/edit.svg
  frontend/src/assets/icons/paperclip.svg
  frontend/src/assets/icons/smile.svg
  frontend/src/assets/icons/trash.svg
  frontend/src/assets/icons/xSquare.svg
  frontend/src/components/ControlHeader/IssueToolBar.jsx
  frontend/src/components/Dashboard/DetailIssue.jsx
  frontend/src/components/Dashboard/DetailIssue.module.css
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/IssueTable.jsx
  frontend/src/components/Dashboard/TitleAndButtons.jsx
  frontend/src/components/Dashboard/TitleAndButtons.module.css
  frontend/src/components/Dashboard/WriteIssue.jsx
  frontend/src/components/Dashboard/WriteIssue.module.css
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Header.module.css
  frontend/src/components/common/Comment.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/CommentInput.module.css
  frontend/src/components/common/FilterBox.jsx
  frontend/src/components/common/FilterBox.module.css
  frontend/src/components/common/PopupList.jsx
  frontend/src/components/common/TitleEditor.jsx
  frontend/src/components/common/TitleEditor.module.css
  frontend/src/components/common/comment.module.css
  frontend/src/constants/link.js
  frontend/src/hooks/useFilterBox.js
  frontend/src/pages/Home/Home.jsx
  frontend/vite.config.js
Labels: feat, FE

#54 [Chore] 깃헙 액션 워크플로우 수정
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  .github/workflows/deploy.yml
Labels: Chore, BE

#55 [Fix] 리뷰내용 반영 리팩토링 및 버그 수정
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3FileService.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentController.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentService.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/dto/CommentResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Comment.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Issue.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Label.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/IssueStatusUpdateException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/InvalidRequestException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/IssueStatusUpdateException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/AssigneeNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/CommentNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/DataNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/IssueNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/LabelNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/MilestoneNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelController.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneController.java
  backend/src/main/java/codesquad/team4/issuetracker/response/ApiResponse.java
  backend/src/main/java/codesquad/team4/issuetracker/user/AssigneeDao.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserController.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserDao.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/codesquad/team4/issuetracker/comment/CommentServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceH2Test.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceUpdateTest.java
  backend/src/test/java/codesquad/team4/issuetracker/util/TestDataHelper.java
  backend/src/test/resources/schema-test.sql
Labels: bug, refactor, BE

#56 [REFACTOR] 리뷰 내용 반영 및 리팩토링
  backend/.editorconfig
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceH2Test.java
Labels: refactor, BE

#57 feat : 이슈 삭제 기능 구현
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceH2Test.java
Labels: feat, BE

#59 [Refactor] 리뷰 반영 및 오류 수정
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  .github/workflows/deploy.yml
  backend/.editorconfig
  backend/src/main/java/codesquad/team4/issuetracker/aws/S3FileService.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentController.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentRepository.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/CommentService.java
  backend/src/main/java/codesquad/team4/issuetracker/comment/dto/CommentResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Comment.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Issue.java
  backend/src/main/java/codesquad/team4/issuetracker/entity/Label.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/IssueStatusUpdateException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/FileUploadException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/InvalidRequestException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/IssueStatusUpdateException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/AssigneeNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/CommentNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/DataNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/IssueNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/LabelNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/notfound/MilestoneNotFoundException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueResponseDto.java
  backend/src/main/java/codesquad/team4/issuetracker/label/LabelController.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneController.java
  backend/src/main/java/codesquad/team4/issuetracker/response/ApiResponse.java
  backend/src/main/java/codesquad/team4/issuetracker/user/AssigneeDao.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserController.java
  backend/src/main/java/codesquad/team4/issuetracker/user/UserDao.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/codesquad/team4/issuetracker/comment/CommentServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceH2Test.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceUpdateTest.java
  backend/src/test/java/codesquad/team4/issuetracker/util/TestDataHelper.java
  backend/src/test/resources/schema-test.sql
Labels: BE

#58 [FEAT ]Feature/issue detail 중간 점검
  frontend/src/components/Dashboard/DetailIssue.jsx
  frontend/src/components/Dashboard/DetailIssue.module.css
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/WriteIssue.jsx
  frontend/src/components/common/Comment.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/CommentInput.module.css
  frontend/src/components/common/FilterBox.jsx
  frontend/src/components/common/FilterBox.module.css
  frontend/src/components/common/comment.module.css
  frontend/src/pages/Home/Home.jsx
Labels: feat, FE

#69 [FEAT] 이슈 상세 화면
  frontend/src/components/Dashboard/DetailIssue.jsx
  frontend/src/components/Dashboard/DetailIssue.module.css
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/WriteIssue.jsx
  frontend/src/components/common/Comment.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/CommentInput.module.css
  frontend/src/components/common/FilterBox.jsx
  frontend/src/components/common/FilterBox.module.css
  frontend/src/components/common/comment.module.css
  frontend/src/pages/Home/Home.jsx
Labels: feat, FE

#72 [Chore] API 확인 후 수정 안한 부분 수정
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/IssueTable.jsx
  frontend/src/components/common/PopupList.jsx
  frontend/src/pages/Home/Home.jsx
Labels: Chore, FE

#73 [Feat] 필터링 기능 구현
  backend/.gitignore
  backend/src/main/java/codesquad/team4/issuetracker/exception/ExceptionMessage.java
  backend/src/main/java/codesquad/team4/issuetracker/exception/badrequest/InvalidFilteringConditionException.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueController.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueDao.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueService.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/dto/IssueRequestDto.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueControllerTest.java
  backend/src/test/java/codesquad/team4/issuetracker/issue/IssueServiceH2Test.java
  backend/src/test/java/codesquad/team4/issuetracker/util/TestDataHelper.java
Labels: feat, BE

#88 [REFACTOR] 리뷰 반영 리팩토링
  backend/src/main/java/codesquad/team4/issuetracker/count/CountDao.java
  backend/src/main/java/codesquad/team4/issuetracker/count/CountService.java
  backend/src/main/java/codesquad/team4/issuetracker/count/Listener/IssueCountListener.java
  backend/src/main/java/codesquad/team4/issuetracker/count/Listener/MilestoneCountListener.java
  backend/src/main/java/codesquad/team4/issuetracker/issue/IssueEvent.java
  backend/src/main/java/codesquad/team4/issuetracker/milestone/MilestoneEvent.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/codesquad/team4/issuetracker/milestone/MilestoneServiceTest.java
  backend/src/test/java/codesquad/team4/issuetracker/util/TestDataHelper.java
  backend/src/test/resources/schema-test.sql
Labels: refactor, BE

#90 [FEAT] 레이블 마일스톤 UI 구현 및 마일스톤 추가, 편집, 삭제 기능 구현
  frontend/src/App.jsx
  frontend/src/assets/icons/calendar.svg
  frontend/src/assets/icons/label.svg
  frontend/src/assets/icons/refreshCcw.svg
  frontend/src/components/ControlHeader/IssueToolBar.jsx
  frontend/src/components/ControlHeader/IssueToolBar.module.css
  frontend/src/components/ControlHeader/LabelAndMilestone.jsx
  frontend/src/components/ControlHeader/LabelAndMilestone.module.css
  frontend/src/components/Dashboard/DetailIssue.jsx
  frontend/src/components/Dashboard/IssueList.jsx
  frontend/src/components/Dashboard/IssueTable.jsx
  frontend/src/components/Dashboard/TableHeader.jsx
  frontend/src/components/Dashboard/WriteIssue.jsx
  frontend/src/components/Dashboard/WriteIssue.module.css
  frontend/src/components/Header/Header.jsx
  frontend/src/components/common/AddLabel.jsx
  frontend/src/components/common/AddLabel.module.css
  frontend/src/components/common/AddMilestone.jsx
  frontend/src/components/common/AddMilestone.module.css
  frontend/src/components/common/Comment.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/CommentInput.module.css
  frontend/src/components/common/FilterBox.jsx
  frontend/src/components/common/LabelElement.jsx
  frontend/src/components/common/LabelElement.module.css
  frontend/src/components/common/MilestoneElement.jsx
  frontend/src/components/common/MilestoneElement.module.css
  frontend/src/components/common/TitleEditor.jsx
  frontend/src/components/common/comment.module.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/LabelPage.jsx
  frontend/src/pages/LabelPage.module.css
  frontend/src/pages/MilestonePage.jsx
  frontend/src/pages/MilestonePage.module.css
  frontend/src/styles/reset.css
  frontend/src/utils/colorUtils.js
  frontend/src/utils/getTimeAgo.js
Labels: feat, FE
